### ISSUE TITLE
[BUG]: Signing of Python package doesn't work

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#55]
### Describe the Bug

After uploading the python package to PyPi, the package cannot be signed.

### Steps to Reproduce

To reproduce this, you need to trigger the package release flow. This can be done by creating a new release on the GitHub home page of the FinTorch repository. 

### Package Version

N/A

### Python Version

N/A

### Environment Details (Optional)

N/A

### Error Logs or Traceback (Optional)

We get the following error
```
Run /home/runner/work/_actions/sigstore/gh-action-sigstore-python/v1.2.3/action.py "./dist/*.tar.gz ./dist/*.whl"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/__main__.py", line 20, in <module>
    from sigstore._cli import main
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_cli.py", line 34, in <module>
    from sigstore._internal.rekor.client import (
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/client.py", line 33, in <module>
    from sigstore._internal.tuf import TrustUpdater
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 42, in <module>
    from tuf.ngclient import RequestsFetcher, Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/__init__.py", line 14, in <module>
    from tuf.ngclient.updater import Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/updater.py", line 48, in <module>
    from tuf.api.metadata import (
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/runner/.local/lib/python3.10/site-packages/securesystemslib/__init__.py)
```
See here the full log: https://github.com/AI4FinTech/FinTorch/actions/runs/9526932333/job/26262984892

### Additional Information (Optional)

- [ ] I have searched for similar issues.
- [X] I am willing to help debug further.

**Comment by boersmamarcel** [comment]
solved
